/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error':                        '#ba1a1a',
        'surface-tint':                 '#2d6196',
        'surface-dim':                  '#cedbf0',
        'on-primary-fixed-variant':     '#08497c',
        'on-tertiary-fixed':            '#001d36',
        'on-primary':                   '#ffffff',
        'surface':                      '#f8f9ff',
        'secondary-fixed-dim':          '#c0c7cc',
        'error-container':              '#ffdad6',
        'on-secondary-container':       '#5c6468',
        'background':                   '#f8f9ff',
        'surface-container-lowest':     '#ffffff',
        'surface-container':            '#e6eeff',
        'surface-container-highest':    '#d7e3f9',
        'on-surface':                   '#101c2c',
        'on-secondary-fixed-variant':   '#41484c',
        'primary-fixed':                '#d2e4ff',
        'on-secondary':                 '#ffffff',
        'surface-bright':               '#f8f9ff',
        'primary-container':            '#2b5f94',
        'outline-variant':              '#c2c7d1',
        'secondary':                    '#585f64',
        'surface-variant':              '#d7e3f9',
        'surface-container-low':        '#eff4ff',
        'on-surface-variant':           '#42474f',
        'on-primary-fixed':             '#001c37',
        'inverse-primary':              '#a0c9ff',
        'secondary-fixed':              '#dce3e8',
        'on-tertiary-fixed-variant':    '#00497c',
        'tertiary-container':           '#226097',
        'on-error':                     '#ffffff',
        'tertiary':                     '#00487a',
        'on-secondary-fixed':           '#151d20',
        'on-tertiary-container':        '#bbd9ff',
        'on-tertiary':                  '#ffffff',
        'tertiary-fixed-dim':           '#9dcaff',
        'secondary-container':          '#dae1e6',
        'primary':                      '#05477b',
        'inverse-surface':              '#253141',
        'on-background':                '#101c2c',
        'primary-fixed-dim':            '#a0c9ff',
        'on-primary-container':         '#bcd8ff',
        'outline':                      '#727780',
        'surface-container-high':       '#dde9ff',
        'on-error-container':           '#93000a',
        'inverse-on-surface':           '#eaf1ff',
        'tertiary-fixed':               '#d1e4ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        'margin-mobile':  '16px',
        'margin-desktop': '32px',
        'stack-lg':       '24px',
        'sidebar-width':  '280px',
        'container-max':  '1440px',
        'gutter':         '24px',
        'stack-sm':       '8px',
        'stack-md':       '16px',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'label-sm':    ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-bold':  ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-md':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg':  ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'body-lg':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
